# Generated by Django 6.0.3 on 2026-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutsection_skillcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='📧', help_text='Add any emoji/icon text. Example: 📞, 📧, 📍, 🌐', max_length=30)),
                ('title', models.CharField(help_text='Example: Phone, Email, Location, Website', max_length=100)),
                ('value', models.CharField(help_text='The contact detail text shown on the website.', max_length=255)),
                ('link', models.CharField(blank=True, help_text='Optional clickable link. Examples: tel:+60123456789, mailto:name@gmail.com, https://example.com', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Only active contact details are shown on the website.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first.')),
            ],
            options={
                'verbose_name': 'Contact Detail',
                'verbose_name_plural': 'Contact Details',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Contact Us', help_text='Small label shown above the contact heading.', max_length=80)),
                ('heading', models.CharField(default="Let's Connect & Collaborate", help_text='Main heading shown on the contact page.', max_length=160)),
                ('description', models.TextField(default='Feel free to contact me for projects, collaborations, or job opportunities.', help_text='Short description shown below the heading.')),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Paste the GitHub repository URL here.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_latest',
            field=models.BooleanField(default=False, help_text='Turn this on to show the project on the home page. If none are selected, the newest projects are shown.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Paste the live website/project URL here.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(help_text='Separate technologies with commas. Example: HTML, CSS, JavaScript, Django', max_length=255),
        ),
    ]
