# Generated by Django 6.0.3 on 2026-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactdetail_contactpagecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Portfolio', help_text='Small label shown above the home page project heading.', max_length=80)),
                ('heading', models.CharField(default='Featured Projects', help_text='Main heading shown above the home page project cards.', max_length=160)),
                ('description', models.TextField(blank=True, default='Projects added from Django Admin are shown here with screenshots, details, live links, and GitHub links.', help_text='Optional short description shown under the project heading.')),
                ('button_text', models.CharField(default='View More Projects', help_text='Button text shown below home page project cards.', max_length=80)),
                ('is_visible', models.BooleanField(default=True, help_text='Turn off to hide the home page project heading.')),
            ],
            options={
                'verbose_name': 'Home Project Section Content',
                'verbose_name_plural': 'Home Project Section Content',
            },
        ),
    ]
