# Generated by Django 6.0.3 on 2026-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_homeprojectsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Portfolio', help_text='Small label shown above the projects page heading.', max_length=80)),
                ('heading', models.CharField(default='My Projects', help_text='Main heading shown on the projects page.', max_length=160)),
                ('description', models.TextField(blank=True, default='A collection of projects added from Django Admin with screenshots, live links, and GitHub links.', help_text='Optional short description shown under the projects page heading.')),
                ('is_visible', models.BooleanField(default=True, help_text='Turn off to hide the projects page heading.')),
            ],
            options={
                'verbose_name': 'Projects Page Content',
                'verbose_name_plural': 'Projects Page Content',
            },
        ),
    ]
